### ISSUE TITLE
missing a LICENSE file

### ISSUE THREAD

**Issue by jdef** [ClusterHQ/flocker-go#1]
I'm assuming that this is apache-v2 licensed like flocker. If so, please add a license file to the repo

**Comment by roberthbailey** [comment]
+1. We need a license file so that the go client can be included in kubernetes. 

@goltermann

**Comment by goltermann** [comment]
Yes.  I assume this is governed by the same LICENSE file in https://github.com/ClusterHQ/flocker/blob/master/LICENSE, but one should be added to this repo.  

@agonzalezro since you seem to have checked in most of the original files.

**Comment by lukemarsden** [comment]
fixed in https://github.com/ClusterHQ/flocker-go/commit/1c0a791b33bdc01d062b376612aa04e27eed7eb3 thanks @goltermann @jdef @roberthbailey !
