### ISSUE TITLE
set up circle-ci to show up on PR pages

### ISSUE THREAD

**Issue by lukemarsden** [ClusterHQ/flocker-go#3]
@agonzalezro any idea how to do this? Did you set up Circle in the first place?

Thanks!

**Comment by agonzalezro** [comment]
Hi @lukemarsden,

I can activate it, I think that it's this option: "Permissive building of fork pull requests".

However, there are some concerns (from the documentation):

> Run builds of fork pull request changes with this project's configuration. CircleCI will automatically update the commit status shown on GitHub's pull request page.
> 
> There are serious security concerns with this setting (see [the documentation](https://circleci.com/docs/fork-pr-builds) for details.) If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you!

I don't see it problematic at all. But it's your call. Also, I think that having admin access to this repo you can do it yourself as well: https://circleci.com/gh/ClusterHQ/flocker-go/edit#experimental

Let me know if it works.

**Comment by lukemarsden** [comment]
Got it, thanks. I changed the setting. I think for this repo it's fine.
